name = "Catppuccin Macchiato"
is_dark = true

[styles]
  [styles.Default]
    fg = "#cad3f5"
    bg = "#24273a"
  [styles.SearchHighlight]
    fg = "#1e2030"
    bg = "#eed49f"
  [styles.Selection]
    fg = "#24273a"
    bg = "#8087a2"
    reverse = true
  [styles.StatusBar]
    fg = "#cad3f5"
    bg = "#1e2030"
  [styles.StatusBarFind]
    fg = "#a6da95"
    bg = "#1e2030"
    bold = true
  [styles.StatusBarMessage]
    fg = "#cad3f5"
    bg = "#1e2030"
    bold = true
  [styles.StatusBarModified]
    fg = "#eed49f"
    bg = "#1e2030"
  [styles.attribute]
    fg = "#f5a97f"
    bg = "#24273a"
  [styles.boolean]
    fg = "#f5a97f"
    bg = "#24273a"
    italic = true
  [styles.builtin]
    fg = "#f5a97f"
    bg = "#24273a"
    italic = true
  [styles.call]
    fg = "#8aadf4"
    bg = "#24273a"
    italic = true
  [styles.character]
    fg = "#a6da95"
    bg = "#24273a"
  [styles.comment]
    fg = "#939ab7"
    bg = "#24273a"
    italic = true
  [styles.conditional]
    fg = "#c6a0f6"
    bg = "#24273a"
    bold = true
  [styles.constant]
    fg = "#f5a97f"
    bg = "#24273a"
  [styles.constructor]
    fg = "#8aadf4"
    bg = "#24273a"
    italic = true
  [styles.control]
    fg = "#c6a0f6"
    bg = "#24273a"
    bold = true
  [styles.definition]
    fg = "#8aadf4"
    bg = "#24273a"
    italic = true
  [styles.escape]
    fg = "#f5bde6"
    bg = "#24273a"
  [styles.function]
    fg = "#8aadf4"
    bg = "#24273a"
    italic = true
  [styles.import]
    fg = "#a6da95"
    bg = "#24273a"
  [styles.keyword]
    fg = "#c6a0f6"
    bg = "#24273a"
    italic = true
  [styles.label]
    fg = "#8aadf4"
    bg = "#24273a"
  [styles.member]
    fg = "#cad3f5"
    bg = "#24273a"
  [styles.module]
    fg = "#eed49f"
    bg = "#24273a"
    italic = true
  [styles.namespace]
    fg = "#eed49f"
    bg = "#24273a"
    italic = true
  [styles.number]
    fg = "#f5a97f"
    bg = "#24273a"
  [styles.operator]
    fg = "#8bd5ca"
    bg = "#24273a"
  [styles.punctuation]
    fg = "#939ab7"
    bg = "#24273a"
  [styles.repeat]
    fg = "#c6a0f6"
    bg = "#24273a"
    bold = true
  [styles.string]
    fg = "#a6da95"
    bg = "#24273a"
  [styles.type]
    fg = "#eed49f"
    bg = "#24273a"
    italic = true
  [styles.variable]
    fg = "#cad3f5"
    bg = "#24273a"
